eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id : UNIVERSITY-SERVICE
          uri: lb://UNIVERSITY-SERVICE
          predicates:
            - Path=/api/v1/university/**
        - id: USER-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/user/**
        - id: USER-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/auth/**
        - id: USER-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/otp/**


server:
  port: 9092
